# $FreeBSD$

PORTNAME=	cms_scanner
PORTVERSION=	0.0.39.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=     rihaz.jerrin@gmail.com
COMMENT=	Framework to provide an easy way to implement CMS Scanners

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activesupport5>=5.1.6:devel/rubygem-activesupport5 \
	        rubygem-addressable>=2.5.2:www/rubygem-addressable \
	        rubygem-nokogiri>=1.8.4:textproc/rubygem-nokogiri \
		rubygem-opt_parse_validator>=0.0.16.1:devel/rubygem-opt_parse_validator \
		rubygem-public_suffix>=3.0.3:dns/rubygem-public_suffix \
		rubygem-ruby-progressbar>=1.9.0:devel/rubygem-ruby-progressbar \
		rubygem-typhoeus>=1.3.0:www/rubygem-typhoeus \
		rubygem-yajl-ruby>=1.3.0:devel/rubygem-yajl-ruby

USES=		gem

NO_ARCH=	yes
USE_RUBY=	yes
RUBY_VER=	2.4

.include <bsd.port.mk>
